name = "remix-unstable-vite-cloudflare-workers"

main = "./app/server.mjs"
assets = "./build/client"
workers_dev = true
compatibility_date = "2023-04-20"
# might be easier to debug without minify
minify = true

# resource created via
#   npx wrangler kv:namespace create kv
# (NOTE: preview_id is not necessary for local preview since https://github.com/cloudflare/workers-sdk/pull/3901)
[[kv_namespaces]]
binding = "kv"
id = "583c3ad45f3c4baeb48e901e1cd8ad12"

# https://developers.cloudflare.com/workers/configuration/environment-variables/#environment-variables
# https://developers.cloudflare.com/workers//wrangler/commands/#secret
[vars]
SOME_VAR="hello"
